steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-west1-docker.pkg.dev/${PROJECT_ID}/my-repo/gah-gee-run:$COMMIT_SHA
      - app

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-west1-docker.pkg.dev/${PROJECT_ID}/my-repo/gah-gee-run:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    timeout: 240s
    args:
      - run
      - deploy
      - gah-gee-run
      - --image=us-west1-docker.pkg.dev/${PROJECT_ID}/my-repo/gah-gee-run:$COMMIT_SHA
      - --command=/app/entrypoint2.sh
      - --args=foo,bar,baz
      - --set-env-vars=ENV=preprod
      - --set-env-vars=TAG=$COMMIT_SHA
      - --set-env-vars=FEATURES=some;preprod;features
      - --set-env-vars=SECRETS=some;preprod;secrets;todostopleakinginversioncontrol!
      - --project=${PROJECT_ID}
      - --no-allow-unauthenticated
      - --region=us-west1
      - --platform=managed
